import type { CollectionSlug, GlobalSlug, Payload, PayloadRequest } from 'payload'

import type { Address, Category, Media, Product, Transaction } from '@/payload-types'

import { contactFormData } from './contact-form'
import { contactPageData } from './contact-page'
import { designData, seedDesigns } from './designs'
import { homePageData } from './home'
import { seedPhoneModels } from './phoneModels'
import { darkHeroPNG, uvCheckerPNG } from './textures'

/**
 * Seeds a small, fully synthetic catalog:
 *
 *   - phone models (three active, two coming soon)
 *   - three designs, each with generated UV-checker artwork and "renders"
 *   - one variant per design × active phone model (created by the hooks, not here)
 *   - a demo customer with two addresses
 *   - home + contact pages
 *
 * No borrowed imagery. Every pixel is generated so nothing here can leak an
 * unlicensed asset onto a public URL.
 */

const collections: CollectionSlug[] = [
  'categories',
  'media',
  'pages',
  'products',
  'forms',
  'form-submissions',
  'variants',
  'variantOptions',
  'variantTypes',
  'carts',
  'transactions',
  'addresses',
  'orders',
  'phoneModels',
  'artwork',
  'productionAssets',
]

const globals: GlobalSlug[] = ['header', 'footer']

const baseAddressUSData: Transaction['billingAddress'] = {
  title: 'Dr.',
  firstName: 'Otto',
  lastName: 'Octavius',
  phone: '1234567890',
  company: 'Oscorp',
  addressLine1: '123 Main St',
  addressLine2: 'Suite 100',
  city: 'New York',
  state: 'NY',
  postalCode: '10001',
  country: 'US',
}

const baseAddressUKData: Transaction['billingAddress'] = {
  title: 'Mr.',
  firstName: 'Oliver',
  lastName: 'Twist',
  phone: '1234567890',
  addressLine1: '48 Great Portland St',
  city: 'London',
  postalCode: 'W1W 7ND',
  country: 'GB',
}

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')

export const seed = async ({
  payload,
  req,
}: {
  payload: Payload
  req: PayloadRequest
}): Promise<void> => {
  payload.logger.info('Seeding database...')

  payload.logger.info(`— Clearing collections and globals...`)

  await Promise.all(
    globals.map((global) =>
      payload.updateGlobal({
        slug: global,
        data: {
          navItems: [],
        },
        depth: 0,
        context: {
          disableRevalidate: true,
        },
      }),
    ),
  )

  for (const collection of collections) {
    await payload.db.deleteMany({ collection, req, where: {} })
    if (payload.collections[collection].config.versions) {
      await payload.db.deleteVersions({ collection, req, where: {} })
    }
  }

  payload.logger.info(`— Seeding customer...`)

  await payload.delete({
    collection: 'users',
    depth: 0,
    where: {
      email: {
        equals: 'customer@example.com',
      },
    },
  })

  const customer = await payload.create({
    collection: 'users',
    data: {
      name: 'Customer',
      email: 'customer@example.com',
      password: 'password',
      roles: ['customer'],
    },
  })

  payload.logger.info(`— Seeding site imagery...`)

  const siteHero = await payload.create({
    collection: 'media',
    data: { alt: 'Dark gradient background' },
    file: await darkHeroPNG({ name: 'site-hero' }),
  })

  payload.logger.info(`— Seeding collections...`)

  const collectionNames = Array.from(new Set(seedDesigns.map((d) => d.collection)))
  const categoriesByName = new Map<string, Category>()

  for (const name of collectionNames) {
    const category = await payload.create({
      collection: 'categories',
      data: { title: name, slug: slugify(name) },
    })
    categoriesByName.set(name, category)
  }

  payload.logger.info(`— Seeding phone models (variant type + options come from hooks)...`)

  for (const model of seedPhoneModels) {
    await payload.create({
      collection: 'phoneModels',
      data: model,
      depth: 0,
      req,
    })
  }

  payload.logger.info(`— Seeding designs (variants come from hooks)...`)

  const products: Product[] = []

  for (const design of seedDesigns) {
    const { hue, collection, ...rest } = design

    const artwork = await payload.create({
      collection: 'artwork',
      data: {
        license: 'original',
        designer: 'Generated UV checker',
        colorProfile: 'sRGB',
        dpi: 300,
        licenseNotes: 'Synthetic test texture generated by the seed script.',
      },
      file: await uvCheckerPNG({
        name: `${design.slug}-print-master`,
        width: 1200,
        height: 2400,
        hue,
        caption: 'PRINT MASTER',
      }),
    })

    const renderFor = async (camera: string, width: number, height: number, caption: string) =>
      payload.create({
        collection: 'media',
        data: { alt: `${design.title} — ${camera} render placeholder (UV checker)` },
        file: await uvCheckerPNG({
          name: `${design.slug}_${camera}`,
          width,
          height,
          hue,
          cols: 6,
          rows: Math.round((6 * height) / width),
          caption,
        }),
      })

    const [hero, threeQuarter, flat] = await Promise.all([
      renderFor('hero', 1400, 1400, 'HERO'),
      renderFor('three_quarter', 1400, 1400, '3/4'),
      renderFor('flat', 1000, 2000, 'FLAT'),
    ])

    const product = await payload.create({
      collection: 'products',
      depth: 0,
      req,
      data: designData({
        ...rest,
        artwork,
        hero: hero as Media,
        threeQuarter: threeQuarter as Media,
        flat: flat as Media,
        collections: [categoriesByName.get(collection)!],
      }),
    })

    products.push(product)
  }

  // Cross-link related designs now that they all exist
  for (const product of products) {
    await payload.update({
      collection: 'products',
      id: product.id,
      depth: 0,
      req,
      data: {
        relatedProducts: products.filter((p) => p.id !== product.id).map((p) => p.id),
      },
    })
  }

  const variantCount = await payload.count({ collection: 'variants', req })
  payload.logger.info(`— ${variantCount.totalDocs} variants generated`)

  payload.logger.info(`— Seeding contact form...`)

  const contactForm = await payload.create({
    collection: 'forms',
    depth: 0,
    data: contactFormData(),
  })

  payload.logger.info(`— Seeding pages...`)

  const firstHero =
    products[0] && typeof products[0].renders?.hero === 'object'
      ? (products[0].renders.hero as Media)
      : siteHero

  await Promise.all([
    payload.create({
      collection: 'pages',
      depth: 0,
      data: homePageData({
        contentImage: siteHero,
        metaImage: firstHero,
      }),
    }),
    payload.create({
      collection: 'pages',
      depth: 0,
      data: contactPageData({
        contactForm: contactForm,
      }),
    }),
  ])

  payload.logger.info(`— Seeding addresses...`)

  await payload.create({
    collection: 'addresses',
    depth: 0,
    data: {
      customer: customer.id,
      ...(baseAddressUSData as Address),
    },
  })

  await payload.create({
    collection: 'addresses',
    depth: 0,
    data: {
      customer: customer.id,
      ...(baseAddressUKData as Address),
    },
  })

  payload.logger.info(`— Seeding orders (print queue)...`)

  // Variants are created by the product hooks, so look them up by title.
  // Titles are "<design> — <phone model>" (see collections/Variants.ts).
  const findVariant = async (design: string, model: string) => {
    const { docs } = await payload.find({
      collection: 'variants',
      depth: 0,
      limit: 1,
      pagination: false,
      req,
      // Exact match: `contains 'iPhone 17'` would also match 'iPhone 17 Pro'.
      where: { title: { equals: `${design} — ${model}` } },
    })
    const variant = docs[0]
    if (!variant) throw new Error(`Seed: no variant for ${design} / ${model}`)
    return variant
  }

  const orderSpecs: {
    printStatus: 'printed' | 'queued'
    lines: { design: string; model: string; quantity: number }[]
  }[] = [
    {
      // Older order, already printed: shows the printedAt stamp and drops
      // off the queue view.
      printStatus: 'printed',
      lines: [{ design: 'Meridian', model: 'iPhone 17 Pro Max', quantity: 1 }],
    },
    {
      // Fresh order with two lines: what the print queue view is for.
      printStatus: 'queued',
      lines: [
        { design: 'Static Bloom', model: 'iPhone 17 Pro', quantity: 2 },
        { design: 'Low Tide', model: 'iPhone 17', quantity: 1 },
      ],
    },
  ]

  for (const spec of orderSpecs) {
    const items: { product: number; variant: number; quantity: number }[] = []
    let amount = 0

    for (const line of spec.lines) {
      const variant = await findVariant(line.design, line.model)
      const productID =
        typeof variant.product === 'object' ? variant.product.id : variant.product
      items.push({ product: productID, variant: variant.id, quantity: line.quantity })
      amount += (variant.priceInUSD ?? 0) * line.quantity
    }

    const transaction = await payload.create({
      collection: 'transactions',
      depth: 0,
      req,
      data: {
        items,
        amount,
        currency: 'USD',
        status: 'succeeded',
        paymentMethod: 'stripe',
        customer: customer.id,
        customerEmail: customer.email,
        billingAddress: baseAddressUSData,
      },
    })

    const order = await payload.create({
      collection: 'orders',
      depth: 0,
      req,
      data: {
        items,
        amount,
        currency: 'USD',
        status: 'processing',
        customer: customer.id,
        customerEmail: customer.email,
        transactions: [transaction.id],
        shippingAddress: baseAddressUSData,
        // printJobs is filled in by the orders beforeChange hook.
        fulfillment: { printStatus: spec.printStatus },
      },
    })

    await payload.update({
      collection: 'transactions',
      id: transaction.id,
      depth: 0,
      req,
      data: { order: order.id },
    })
  }

  payload.logger.info('Seeded database successfully!')
}
